// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOUIVZ5hbGhYdREv8FL_5jmdX-CKfWyUw',
    appId: '1:622235004313:web:5b989fb1ea7b9f33787708',
    messagingSenderId: '622235004313',
    projectId: 'researchpro-firebase',
    authDomain: 'researchpro-firebase.firebaseapp.com',
    storageBucket: 'researchpro-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVu279KYqaqFMXWfZljtukJvnRYT768pU',
    appId: '1:622235004313:android:ce2b91cee4453afe787708',
    messagingSenderId: '622235004313',
    projectId: 'researchpro-firebase',
    storageBucket: 'researchpro-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8EtHg3VYGp11khim521201G2SoSc77_U',
    appId: '1:622235004313:ios:4c286f945668869a787708',
    messagingSenderId: '622235004313',
    projectId: 'researchpro-firebase',
    storageBucket: 'researchpro-firebase.firebasestorage.app',
    iosBundleId: 'com.example.researchproFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8EtHg3VYGp11khim521201G2SoSc77_U',
    appId: '1:622235004313:ios:4c286f945668869a787708',
    messagingSenderId: '622235004313',
    projectId: 'researchpro-firebase',
    storageBucket: 'researchpro-firebase.firebasestorage.app',
    iosBundleId: 'com.example.researchproFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOUIVZ5hbGhYdREv8FL_5jmdX-CKfWyUw',
    appId: '1:622235004313:web:003e596e12702138787708',
    messagingSenderId: '622235004313',
    projectId: 'researchpro-firebase',
    authDomain: 'researchpro-firebase.firebaseapp.com',
    storageBucket: 'researchpro-firebase.firebasestorage.app',
  );
}
